# Generated by Django 4.0.3 on 2022-03-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_alter_word_en_options_alter_word_en_lvl_know_and_more'),
        ('quote', '0002_rename_word_quote_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(max_length=250, verbose_name='цитата'),
        ),
        migrations.RemoveField(
            model_name='quote',
            name='words',
        ),
        migrations.AddField(
            model_name='quote',
            name='words',
            field=models.ManyToManyField(to='word.word_en', verbose_name='связанные слова'),
        ),
    ]
