# Generated by Django 4.0.3 on 2022-03-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_alter_quote_quote_remove_quote_words_quote_words'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-id'], 'verbose_name': 'цитата', 'verbose_name_plural': 'цитаты'},
        ),
    ]
