# Generated by Django 4.0.3 on 2022-03-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=25)),
                ('translation', models.TextField()),
                ('lvl_know', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
