# Generated by Django 4.0.3 on 2022-03-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_alter_quote_options'),
        ('word', '0006_alter_word_en_word'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word_en',
            new_name='WordEn',
        ),
        migrations.AlterModelOptions(
            name='worden',
            options={'ordering': ['-id'], 'verbose_name': 'слово', 'verbose_name_plural': 'слова'},
        ),
    ]
