# Generated by Django 4.0.3 on 2022-03-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word_en',
            options={'ordering': ['lvl_know'], 'verbose_name': 'слово', 'verbose_name_plural': 'слова'},
        ),
        migrations.AlterField(
            model_name='word_en',
            name='lvl_know',
            field=models.SmallIntegerField(default=0, verbose_name='уровень знания слова'),
        ),
        migrations.AlterField(
            model_name='word_en',
            name='translation',
            field=models.CharField(max_length=25, verbose_name='перевод'),
        ),
        migrations.AlterField(
            model_name='word_en',
            name='word',
            field=models.CharField(max_length=25, verbose_name='слово'),
        ),
    ]
