# Generated by Django 4.0.3 on 2022-03-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_alter_word_en_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word_en',
            options={'ordering': ['word'], 'verbose_name': 'слово', 'verbose_name_plural': 'слова'},
        ),
    ]
