# Generated by Django 4.0.3 on 2022-03-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_alter_word_en_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_en',
            name='word',
            field=models.CharField(max_length=25, unique=True, verbose_name='слово'),
        ),
    ]
