# Generated by Django 4.0.3 on 2022-03-29 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, unique=True, verbose_name='Предложение')),
                ('translation', models.TextField(max_length=200, verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'предложения',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(max_length=30, unique=True, verbose_name='Время')),
                ('info', models.TextField(default='', verbose_name='Инфо')),
            ],
            options={
                'verbose_name': 'время',
                'verbose_name_plural': 'времена',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_answer', models.TextField(default='', verbose_name='последний ответ')),
                ('total_answers', models.IntegerField(default=0, verbose_name='ответов всего')),
                ('right_answers', models.IntegerField(default=0, verbose_name='правильных ответов')),
                ('wrong_answers', models.IntegerField(default=0, verbose_name='неправильные ответы')),
                ('last_example', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastexample', to='tenses.example', verbose_name='последний вопрос')),
                ('now_example', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noweample', to='tenses.example', verbose_name='текущий вопроc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'данные пользователя',
                'verbose_name_plural': 'данные пользователей',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='example',
            name='tense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenses.tense'),
        ),
    ]
