# Generated by Django 4.0.3 on 2022-03-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(max_length=30, unique=True, verbose_name='Время')),
                ('info', models.TextField(default='', verbose_name='Инфо')),
            ],
            options={
                'verbose_name': 'время',
                'verbose_name_plural': 'времена',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, unique=True, verbose_name='Предложение')),
                ('translation', models.TextField(max_length=200, verbose_name='Перевод')),
                ('tense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenses.tense')),
            ],
            options={
                'verbose_name': 'предложение',
                'verbose_name_plural': 'предложения',
                'ordering': ['-id'],
            },
        ),
    ]
