# Generated by Django 4.0.3 on 2022-03-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.JSONField(null=True, verbose_name='история'),
        ),
    ]
