# Generated by Django 4.0.3 on 2022-03-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenses', '0002_profile_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
