# Generated by Django 4.0.3 on 2022-03-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenses', '0004_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='pronunciation',
            field=models.ImageField(null=True, upload_to='audio/examples/%Y/%m/%d/'),
        ),
    ]
