# Generated by Django 4.0.3 on 2022-03-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenses', '0006_alter_example_pronunciation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='now_example',
        ),
        migrations.AddField(
            model_name='profile',
            name='history_word',
            field=models.JSONField(null=True, verbose_name='история'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_example',
            field=models.JSONField(null=True, verbose_name='история'),
        ),
    ]
