# Generated by Django 4.0.3 on 2022-03-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenses', '0007_remove_profile_now_example_profile_history_word_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_example',
            new_name='history1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_answer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='right_answers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_answers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wrong_answers',
        ),
        migrations.AddField(
            model_name='profile',
            name='history2',
            field=models.JSONField(null=True, verbose_name='история'),
        ),
        migrations.AddField(
            model_name='profile',
            name='history3',
            field=models.JSONField(null=True, verbose_name='история'),
        ),
        migrations.AddField(
            model_name='profile',
            name='history4',
            field=models.JSONField(null=True, verbose_name='история'),
        ),
        migrations.AddField(
            model_name='profile',
            name='history5',
            field=models.JSONField(null=True, verbose_name='история'),
        ),
        migrations.AddField(
            model_name='profile',
            name='history_audio',
            field=models.JSONField(null=True, verbose_name='история'),
        ),
    ]
